# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb3beb5a0bf562a3d4b5fc2f78da023cb2bd69f574c4c377d266d4c0db68f334325465a1d5b2b29c49d315fafc2c9ffd70eb209617d974d3e2762fe1320fc78f

test:
  secret_key_base: 8d8b42407ebadfbd0ed077e848087be7764ee12e7b467b5516305574bbf03d1de41d244a9b3c985a09cdb22382d3dd880291d32e8f78c41a91649615fa046619

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
